### Registrar usuário
POST https://adonis-julya.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Julya", 
    "email": "julyamodena01@gmail.com", 
    "password": "1234"
}

### Autenticar usuário
POST https://adonis-julya.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "julyamodena01@gmail.com", 
    "password": "1234"
}

### Mensagem Push
POST https://adonis-julya.onrender.com/push HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mzg.kESslQGtjFobY6H40A3Uokw8qCMMI9caKWCxcfxk7Z9eZUjOt0yA1ttpz3bG
{
    "id": 1,
    "title": "Oi",
    "body": "Tudo bem?"
}


