### Registrar usuário
POST https://adonis-julya.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Julya", 
    "email": "julyamodena01@gmail.com", 
    "password": "1234"
}

### Autenticar usuário
POST https://adonis-julya.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "julyamodena01@gmail.com", 
    "password": "1234"
}


